# Generated by Django 4.2.7 on 2023-12-06 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yetkazish_puli', models.PositiveSmallIntegerField(default=5)),
                ('sana', models.DateField(auto_now_add=True)),
                ('umumiy_summa', models.PositiveIntegerField(default=0)),
                ('savat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyurtma.savat')),
            ],
        ),
    ]
