# Generated by Django 4.2.7 on 2023-11-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='tasdiqlangan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='tasdiqlash_kodi',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
