# Generated by Django 4.2.7 on 2023-12-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='manzil',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profil',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
